"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import configureStore from '../store/configureStore'
import { Provider } from 'react-redux'

// const inter = Inter({ subsets: ['latin'] })
const store = configureStore();

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body><Provider store={store}>{children}</Provider></body>
    </html>
  )
}
